version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: planner-postgres
    environment:
      POSTGRES_USER: planner
      POSTGRES_PASSWORD: planner123
      POSTGRES_DB: planner_db
    ports:
      - "5432:5432"
    volumes:
      - planner_pg_data:/var/lib/postgresql/data

volumes:
  planner_pg_data:
